version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/events
permissions:
  - object: /var/www/events
    pattern: '**'
    mode: '0755'
    owner: root
    group: root
    type:
      - file
      - directory
hooks:
  BeforeInstall:
    - location: deploy-scripts/arrange-deployment-folders.sh
      runas: root
  AfterInstall:
    - location: deploy-scripts/db-config.sh
      runas: nginx
    - location: deploy-scripts/install-gems.sh
      runas: nginx
    - location: deploy-scripts/compile-assets.sh
      runas: nginx
    - location: deploy-scripts/run-db-migrations.sh
      runas: nginx
      
  ApplicationStart:
    - location: deploy-scripts/finish-installation.sh
      runas: root