version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/events
permissions:
  - object: /var/www/events
    pattern: '**'
    mode: '0755'
    owner: root
    group: root
    type:
      - file
      - directory
hooks:
  ValidateService:
  - location: deploy-scripts/validate_service.sh
      timeout: 30
      runas: root
  BeforeInstall:
    - location: deploy-scripts/arrange-deployment-folders.sh
      runas: root
  AfterInstall:
    - location: deploy-scripts/db-config.sh
      runas: root
    - location: deploy-scripts/install-gems.sh
      runas: root
    - location: deploy-scripts/compile-assets.sh
      runas: root
    - location: deploy-scripts/run-db-migrations.sh
      runas: root
      
  ApplicationStart:
    - location: deploy-scripts/finish-installation.sh
      runas: root