version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.x
    commands:
      - echo Installing Bundler...
      - gem install bundler
      - bundle install

artifacts:
  base-directory: dist/events
  files:
    - '**/*'