version: 0.2

phases:
  install:
    commands:
      - bundle install
  pre_build:
    commands:
      - export RAILS_ENV=test
  build:
    commands:
      - bundle exec rake db:create
      - bundle exec rake db:schema:load
      - bundle exec rake db:migrate
      - bundle exec rake db:setup
  post_build:
    commands:
      bundle exec test