version: 0.2

phases:
  install:
    runtime-versions:
      ruby: latest
    commands:
      - echo Installing Bundler...
      - bundle install

artifacts:
  base-directory: dist/events
  files:
    - '**/*'