version: 0.2

phases:
  install:
    commands:
      - bundle install
  pre_build:
    commands:
      - export RAILS_ENV=test
      - bundle exec rails webpacker:yarn_install
  build:
    commands:
      - bundle exec rails db:create
      - bundle exec rails db:schema:load
      - bundle exec rails db:migrate
      - bundle exec rails db:setup
      - bundle exec rails webpacker:compile
  post_build:
    commands:
      bundle exec rails test
artifacts:
  base-directory: dist/events
  files:
    - '**/*'